kafka:
  pool: nav-dev
data:
  topic: data-innlop-v2
gcp:
  project: teamdagpenger-dev-885f
pdl:
  host: pdl-api.dev-fss-pub.nais.io
  scope: "api://dev-fss.pdl.pdl-api/.default"
db:
  tier: db-f1-micro

avslag:
  dato: 2025-11-19 # Når vi la til avgjørelse i behandlingsresultat