kafka:
  pool: nav-prod
data:
  topic: data-innlop-v2
gcp:
  project: teamdagpenger-prod-9042
pdl:
  host: pdl-api.prod-fss-pub.nais.io
  scope: "api://prod-fss.pdl.pdl-api/.default"
db:
  tier: db-custom-1-3840

avslag:
  dato: "2026-08-31T08:52:00" # Avslag fom 31.08.2026 eies av dp-sak
