apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: behandling-tilstand
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{project}}
    cnrm.cloud.google.com/state-into-spec: merge

spec:
  resourceID: behandling-tilstand
  description: "Dataprodukt om tid brukt i behandling"
  datasetRef:
    external: dataprodukt
  view:
    useLegacySql: false
    query: >-
      SELECT 
        bt.behandlingId,
        bt.tekniskTid as tilstandEndretTid,
        bt.forrigeTilstand,
        bt.gjeldendeTilstand,
        bt.tidBrukt,
        bt.tidBruktSekund
      FROM `dataprodukt.data_behandling_tilstand_v1` bt
