apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: dagpenger-behandling-anonymisiert
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{project}}
    cnrm.cloud.google.com/state-into-spec: merge

spec:
  resourceID: dagpenger-behandling-anonymisiert
  description: "Dataprodukt som viser alle behandlinger av dagpenger uten sensitiv informasjon"
  datasetRef:
    external: dataprodukt
  view:
    useLegacySql: false
    query: >-
      SELECT b.* EXCEPT (ident, saksbehandler, beslutter, ansvarligEnhet)
      FROM `dataprodukt.data_behandling_beta_v2` b
