apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: dagpengesoknader-ident
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{project}}
    cnrm.cloud.google.com/state-into-spec: merge

spec:
  description: "Dataprodukt som viser alle dagpengesøknader inkludert utenlandstilsnitt og ident"
  datasetRef:
    external: dataprodukt
  view:
    useLegacySql: false
    query: >-
      SELECT
        D.*,
        I.ident
      FROM
        `dataprodukt.dagpengesoknader` D,
        `dataprodukt.data_innlop_ident_v1` I
      WHERE
        D.journalpostId=I.journalpostId