apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: vedtak-avslag
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{project}}
    cnrm.cloud.google.com/state-into-spec: merge

spec:
  resourceID: vedtak-avslag
  description: "Dataprodukt om avslag på dagpenger"
  datasetRef:
    external: dataprodukt
  view:
    useLegacySql: false
    query: >-
      SELECT behandlingId,
             fagsakId,
             behandletHendelse.id as soknadId,
             ident,
             automatisk,
             vedtakstidspunkt,
             opprettetTid,
             string_agg(vilkaar.navn) as grunnAvslag
      FROM  `dataprodukt.data_vedtak_beta_v1` AS vedtak,
            UNNEST(vilkaar) as vilkaar
      WHERE fastsatt.utfall is false
      AND   behandletHendelse.type = 'Søknad'
      AND   vilkaar.status = 'IkkeOppfylt'
      GROUP BY behandlingId, fagsakId, behandletHendelse.id, ident, automatisk, vedtakstidspunkt, opprettetTid;
