apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: vedtak-samordning
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{project}}
    cnrm.cloud.google.com/state-into-spec: merge

spec:
  resourceID: vedtak-samordning
  description: "Dataprodukt som viser samordning i vedtak"
  datasetRef:
    external: dataprodukt
  view:
    useLegacySql: false
    query: >-
      SELECT behandlingId,
             samordning.type,
             samordning.`beløp`,
             samordning.grad
      FROM `dataprodukt.data_vedtak_beta_v1` AS vedtak,
           UNNEST(fastsatt.samordning) AS samordning
      WHERE behandletHendelse.type = 'Søknad';
  