apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: vedtak-innvilget-anonymisiert
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{project}}
    cnrm.cloud.google.com/state-into-spec: merge

spec:
  resourceID: vedtak-innvilget-anonymisiert
  description: "Dataprodukt om innvilgede vedtak om dagpenger uten ident"
  datasetRef:
    external: dataprodukt
  view:
    useLegacySql: false
    query: >-
      SELECT behandlingId,
             fagsakId,
             behandletHendelse.id as soknadId,
             vedtakstidspunkt,
             virkningsdato,
             fastsatt.grunnlag.grunnlag,
             fastsatt.grunnlag.begrunnelse as grunnlagBegrunnelse,
             fastsatt.fastsattVanligArbeidstid.vanligArbeidstidPerUke,
             fastsatt.fastsattVanligArbeidstid.nyArbeidstidPerUke,
             fastsatt.sats.dagsatsMedBarnetillegg,
             --antallbarn,
             --stønadstype,
             opprettetTid
      FROM `dataprodukt.data_vedtak_v1` AS vedtak
      WHERE fastsatt.utfall is true
      AND   behandletHendelse.type = 'Søknad';
