apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: vedtak-kvoter
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{project}}
    cnrm.cloud.google.com/state-into-spec: merge

spec:
  resourceID: vedtak-kvoter
  description: "Dataprodukt om kvote i vedtak om dagpenger"
  datasetRef:
    external: dataprodukt
  view:
    useLegacySql: false
    query: >-
      SELECT behandlingId,
             kvoter.navn,
             kvoter.type,
             kvoter.verdi
      FROM `dataprodukt.data_vedtak_v1` AS vedtak,
           UNNEST(fastsatt.kvoter) AS kvoter;
